### ISSUE TITLE
Modulo 1.4

### ISSUE THREAD

**Issue by eslivan** [SistemasTecTlaxiaco/Ivan#3]
<img width="1440" alt="Captura de pantalla 2023-06-27 a la(s) 11 41 54" src="https://github.com/SistemasTecTlaxiaco/Ivan/assets/137822411/44cdfef1-067e-483b-98fa-28800ebef1b6">

**Comment by josealfredo79** [comment]
Bien hecho y revisado...siga adelante maestro...
