### ISSUE TITLE
asignación modulo 2.2

### ISSUE THREAD

**Issue by eslivan** [SistemasTecTlaxiaco/Ivan#5]
<img width="1440" alt="Captura de pantalla 2023-06-27 a la(s) 13 34 53" src="https://github.com/SistemasTecTlaxiaco/Ivan/assets/137822411/34f1c3c4-5a7a-4246-8a88-88ae79d19a8f">

**Comment by josealfredo79** [comment]
Muy bien...por el trabajo realizado..
