### ISSUE TITLE
"Asignación del módulo 2.3"

### ISSUE THREAD

**Issue by eslivan** [SistemasTecTlaxiaco/Ivan#7]
https://classroom.github.com/a/CFnt7CaO
<img width="1440" alt="Captura de pantalla 2023-06-29 a la(s) 10 07 58" src="https://github.com/SistemasTecTlaxiaco/Ivan/assets/137822411/c54eb44f-e7ea-4127-9e5f-35f516ae554e">

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
